### ISSUE TITLE
Yet another object-to-rdf mapping: java2rdf

### ISSUE THREAD

**Issue by marco-brandizi** [semantalytics/awesome-semantic-web#107]
I've just discovered this GH repository, very interesting!

Not that I want self-promote (well, yes! Partially I want it :-) ), but I think the [java2rdf library](https://github.com/EBIBioSamples/java2rdf) would be worth to be added to the Object/RDF mapping section.

I started writing it a couple of years ago, when none of the few libraries around for the same purpose worked like java2rdf works, that is, by means of mapping declarations made outside the classes being mapped. This can be useful when the source object model is a third party library that you don't (want to) control, and hence you cannot add annotations to it, or you don't want to overload the object model source files with annotations that concern just one particular use of those files. Moreover, while the mappings are declarative, they're still based on Java, ie, you don't need to learn a new XML schema or a domain-specific language, though in future I might decide to support Spring and allow for defining the mappings via the Spring container and XML or Groovy config files.

Hope this will be interesting to the curator of the awesome semantic web!

**Comment by zacharywhitley** [comment]
Please, self-promote. This site is all about highlighting and collecting all the great work that's been done out there. I'm also really interested in filling in those practial gaps that get in the way of using the technology just like you've done. It's also a great way to get people like you to tell me about their cool projects.

**Comment by zacharywhitley** [comment]
You have been added! Thank you for your contribution. If there's anything you feel is missing from the list please feel free to either submit a PR or add it to this issue and I'll make sure it gets on there https://github.com/semantalytics/awesome-semantic-web/issues/81

**Comment by marco-brandizi** [comment]
Thanks a lot, @zacharywhitley!
