### ISSUE TITLE
CfP: Session on Awesome Tools for the Semantic Web at US2TS 2020

### ISSUE THREAD

**Issue by hlapp** [semantalytics/awesome-semantic-web#124]
Since it is highly relevant and in fact was one of the factors inspiring it, I hope people receiving notice for new issues don't consider this spam. In fact, I hope everyone who contributed here considers contributing to the 2020 US2TS session below.

Awesome Tools for the Semantic Web
==================================
A session at US2TS 2020

Do you develop tools, libraries, or other resources that are intended to enable, broaden, or apply semantic web technologies? Are you interested in raising the community’s awareness of them? Do you build (semantic web or not) applications (re)using such resources, and have a story to tell? Or have you tried building such applications and discovered shortcomings in the current tool or library ecosystem?

If your answer is yes to any of the above, please consider attending and contributing to “Fostering an awesome tool ecosystem for the semantic web”, a session at the upcoming US2TS 2020 conference (March 9-11, Raleigh NC, https://us2ts.org). The session aims to foster community awareness of existing resources based on semantic web technologies, and to facilitate the exchange of know-how and common gaps or limitations in current tooling.

We are now inviting contributions in the form of short (5-10 minutes) presentations, in particular for awesome(*) software tools and libraries, and for experiences with building end-user applications. Submit your presentation here:
https://forms.gle/DkVnJ2qgjH1bB4ru7

Review is rolling — acceptance is first-come, first-served until all allocable time for the session is used up. Hence, please submit as early as possible. (Early registration for US2TS 2020 is scheduled to end on January 31, 2020. At least one of the authors needs to attend and be able to present.)

For more details about the session see the (accepted) session proposal: Lapp & Gonçalves, Fostering an awesome tool ecosystem for the semantic web. Authorea. January 03, 2020. https://doi.org/10.22541/au.157807505.51352689

(*) The meaning of awesome includes, but is not limited to, openly available, reusable resources that are potential building blocks contributing to an interoperable ecosystem.

Looking forward to your submissions,

Hilmar Lapp (Duke University) (@hlapp)
Rafael Gonçalves (Stanford University) (@rsgoncalves)

**Comment by zacharywhitley** [comment]
I don't consider it spam as it's highly relevant. Thank you for the notice. I also hope people contributing to us2ts consider adding their contribution to this list if it's not already here.

**Comment by VladimirAlexiev** [comment]
@hlapp or @zacharywhitley can you close this, unless we need to look at workshop results and add tools to the list?
