### ISSUE TITLE
RDF reasoner

### ISSUE THREAD

**Issue by supreme-core** [semantalytics/awesome-semantic-web#269]
Hello,

Love what you've done to compile the resources together on semantic web.

I am interested in finding a reasoner that works well for implicit inferences. I am not particularly impressed with RDFLib. Do you know if you came across any solid choices?

**Comment by RichDijk** [comment]
What is implicit reasoning? You might try Reasonable.

**Comment by zacharywhitley** [comment]
I was going to say the same thing, "What is implicit reasoning?" but now I have a question for you, what is Reasonable? (Terrible name if that's a reasoner. How the heck do you search for that?)

**Comment by zacharywhitley** [comment]
Ok, maybe that wasn't so bad https://github.com/gtfierro/reasonable

**Comment by supreme-core** [comment]
@RichDijk I am not sure what's the agreed technical term in the industry to describe reasoning deriving new knowledge from existing data using logical rules without having explicit facts. 

Several different source was using `derived`, `inferred` and 'implicit' interchangeably. 

CC @zacharywhitley 

Consider the following:
```RDF
:Jon rdf:type :Person .
:Mark rdf:type :Person .
:Jon :hasParent :Mark .
```
OWL statement
```
:hasParent rdfs:subPropertyOf :hasAncestor .
```
I want to be able to infer
```
:Jon :hasAncestor :Mark
```
The OWL statement `:hasParent rdfs:subPropertyOf :hasAncestor` indicates `hasParent` is a subproperty of `hasAncestor`, when referring `hasParent` it also means it is referring `hasAncestor`. 

Since RDF triples did not explicit states `Jon :hasAncestor :Mark`, many of the RDF packages/database is not able to infer `hasAncestor` when there aren't explicitly stored. 

This is just a simple example, it can get very complex very quickly when you are dealing with hundreds of relationships. 

I am hoping to find a solid reasoner. Please recommend 

Thanks

**Comment by vid** [comment]
@supreme-core I think the term you are looking for is 'entailment.'  Here is a list summarized by chatgpt.

{{1. Apache Jena (ARQ)
Supports: RDFS, OWL (partial OWL-Lite and OWL 2 RL)
Details: Apache Jena is a widely used open-source framework for RDF data, including reasoning. It supports RDFS and OWL entailment through a rule-based engine.
License: Apache License 2.0
2. HermiT
Supports: OWL 2 DL
Details: HermiT is a reasoning engine that supports full OWL 2 DL entailment, which can be used for RDF reasoning when RDF data is described using OWL vocabularies.
License: GNU Lesser General Public License (LGPL)
3. Pellet
Supports: OWL 2 DL, RDFS
Details: Pellet is an open-source reasoner that provides reasoning for OWL 2 DL and RDFS entailment. It is commonly used in conjunction with RDF data and ontologies.
License: GNU General Public License (GPL)
4. RDFox (Community Edition)
Supports: RDFS, OWL 2 RL, Datalog
Details: RDFox has an open-source community version that provides support for RDFS and OWL 2 RL entailment and rule-based reasoning with Datalog. It is optimized for parallel reasoning over large datasets.
License: GPL for community version
5. COWL (ClioPatria)
Supports: RDFS, OWL (partial)
Details: ClioPatria, a SWI-Prolog-based Semantic Web framework, includes the COWL reasoner, which supports RDFS and some OWL reasoning for RDF data.
License: Simplified BSD License (for ClioPatria)

All of these reasoners are open-source and support various levels of RDF entailment, with some focused on RDFS reasoning and others on more expressive OWL-based reasoning.}}

**Comment by supreme-core** [comment]
Hi @vid 

These choices seem appropriate for further investigation. 

I know I am going to throw some people off when I use "entailment". Very unique word, it's hard to forget once you hear it.

Much appreciate for the detailed response.
