### ISSUE TITLE
Add #killer-use-cases section

### ISSUE THREAD

**Issue by maximveksler** [semantalytics/awesome-semantic-web#32]
The general idea is to get people excited by what is possible and is already out there.

- https://joernhees.github.io/associations/
- http://solid.inrupt.com

**Comment by amirouche** [comment]
Versioned database ala git :100:

**Comment by zacharywhitley** [comment]
I'm closing this. It's out of scope for an awesome list and if after 20 years of development people still can't find meaningful use cases maybe it wasn't such a good idea after all. Semantic web people need a good smack in the face. There are plenty of use cases. Go figure out why people aren't using it. There are reasons.
