### ISSUE TITLE
Remove Standard > XML Scheme section

### ISSUE THREAD

**Issue by maximveksler** [semantalytics/awesome-semantic-web#38]
I do not think the XML working group standard is directly related to semantic web, especially nowadays when JSON-LD becomes popular.

https://github.com/semantalytics/awesome-semantic-web/blob/master/README.md#xml-schema

I suggest we remove it from the awesome list.

**Comment by maximveksler** [comment]
@ZacharyWhitley what are your thoughts on this?

**Comment by ZacharyWhitley** [comment]
Ya, I agree. I added it just because people like to display it on the semantic web stack https://en.wikipedia.org/wiki/Semantic_Web_Stack

**Comment by maximveksler** [comment]
Maybe we should replace the link of XML with a link to this wikipedia entry? "Semantic Web Stack" as a concept seems useful.

**Comment by ZacharyWhitley** [comment]
Now that I think about it, there's a good case for leaving it in there. It's fundamental to RDF and SPARQL. If you want to understand how datatypes are handled in both these specs you need to know XSD. It's a judgement call. I didn't include URL/URI/IRI but that's there as well. Either way it might be nice to including the cake might be a good idea.

**Comment by maximveksler** [comment]
OK. Would we like to reference to XSD scope for RDF https://www.w3.org/2011/rdf-wg/wiki/XSD_Datatypes ?
