### ISSUE TITLE
Blasegraph status

### ISSUE THREAD

**Issue by zacharywhitley** [semantalytics/awesome-semantic-web#46]
Blazegraph was acquired by Amazon and it's current status is unknown. There haven't been any commits to the repo in a couple of years.

**Comment by maximveksler** [comment]
I'm becoming more convicnece that BlazeGraph is dead. 

How about we created warning signs? 

## Databases

$ - Proprietary  
OS - OpenSource  
F - Free  

- [Jena TDB](http://jena.apache.org/documentation/tdb/index.html) - (OS).
- [Ontotext GraphDB™](http://graphdb.ontotext.com/) - ($/F).
- [Halyard](https://github.com/Merck/Halyard) - (OS).
- [Stardog](http://stardog.com) - ($/F).
- [Strabon](http://www.strabon.di.uoa.gr/)
- [☠️Systap Blazegraph™](https://www.blazegraph.com/) - ($/OS).
  - [docker-blazegraph](https://github.com/zorino/docker-blazegraph)
  - [blazegraph-samples](https://github.com/blazegraph/blazegraph-samples)
  - [docker-blazegraph](https://github.com/lyrasis/docker-blazegraph)
  - [blazegraph-service](https://github.com/vastix/blazegraph-service)
- [Marklogic](https://github.com/marklogic/semantic) - ($).
- [Virtuoso](https://virtuoso.openlinksw.com/) - ($/OS).
  - [virtuoso-opensource](https://github.com/openlink/virtuoso-opensource)

**Comment by ZacharyWhitley** [comment]
haha. Love it. Maybe we should change OS => SOS - Abandonware.

They haven't responded to any posts since they were acquired by Amazon and there was a specific question about the future of the project.

**Comment by maximveksler** [comment]
haha "SOS software" 👍

I think we need to consider perhaps a plan for "in flux" as this being an evolving field. Apache has the concept of incubator where a project needs to form a community and useful code base before it is adapted as an Apache project.

I think that as we are a service for the community we now need to take responsibility for the inventory of this repo, work to define a "precise" value that is to be gained by using the list, and then work for optimising reaching that goal. 

I.e. it's not just an inventory list, it's a list that claims to be the "best option possible", and if one or several projects fall out of these criticise, i.e.

1. No one uses it (yet? ever?)
2. Looks Abandonware (use judgment, you know it when you see it. Hasn't been maintained? No issues reported? documentation is broken / non existing? googling for it doesn't bring any users / results, and co..)
3. Is colliding with much better solutions listed.
4. Blazegraph case (widely used, very popular, has been purchased out of existence)
5. Something else? (doesn't feel right...) 

Then we should decide how we're handling it, we can choose to remote it. If it's very very valuable then keep it by mark it as Abandonware. or maybe push it down to some other "graveyard list"

**Comment by zacharywhitley** [comment]
It looks like there is some discussion about having an opensource version managed by the people at wikidata https://github.com/blazegraph/database/issues/86

**Comment by zacharywhitley** [comment]
There seems to be some activity on this subject. Blazegraph is a significant code base and is deployed at Amazon so I'm going to close this. We can reopen it if something changes.
