### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by maximveksler** [semantalytics/awesome-semantic-web#52]
- [x]   ✖  240:3   Link to https://diuf.unifr.ch/main/xi/diplodocus is dead      no-dead-urls
- [x]   ✖  242:3   Invalid list item link URL                                    awesome/list-item
- [x]   ✖  527:3   Link to http://www.openvest.com/trac/wiki/RDFAlchemy is dead  no-dead-urls
- [x]   ✖  614:3   Link to https://github.com/mattpap/vim-owl-tools is dead      no-dead-urls
- [x]   ✖  657:3   Link to http://opencube-toolkit.eu/ is dead                   no-dead-urls
- [x]   ✖  667:3   Link to https://lod-cloud.net is dead                         no-dead-urls

**Comment by maximveksler** [comment]
@ZacharyWhitley what would you like to do about 

2. - 242:3 `[Yars2]()` I can't find good online references.

**Comment by ZacharyWhitley** [comment]
I had linked a couple of other ones against papers and we could use this one for Yars2 https://pdfs.semanticscholar.org/2b82/cc0aac6efb308408e928a26da8cc59e689eb.pdf

Again it's probably not in the spirit of an awesome list and would be available through a simple literature search. What do you think, shall we clean house and throw away all the old stuff?

**Comment by maximveksler** [comment]
I've added links to semantic schooler for the dead links.
