### ISSUE TITLE
Ha-Sparql project is virtually empty

### ISSUE THREAD

**Issue by jonassmedegaard** [semantalytics/awesome-semantic-web#57]
Recently added Ha-Sparql project contains of an empty README file.

Please drop it, or point to where the project truly is.

**Comment by maximveksler** [comment]
Thank you for the community feedback.

**Comment by maximveksler** [comment]
possibility an unmaintained project ?

**Comment by ZacharyWhitley** [comment]
(Shrug) Maybe.
