### ISSUE TITLE
DREAM system not "federated"?

### ISSUE THREAD

**Issue by kasei** [semantalytics/awesome-semantic-web#60]
The "DREAM" system listed under the "Federated SPARQL" section does not seem to be a federated SPARQL system. Instead, it sounds like a parallel system for clusters.

**Comment by ZacharyWhitley** [comment]
Good catch. Thanks. Looks like it’s clustered not federated. I’ll move it over to the database section.  They also have a link to the google code archive for rdf3x that I’ll have to add.
