### ISSUE TITLE
Improve rules section

### ISSUE THREAD

**Issue by maximveksler** [semantalytics/awesome-semantic-web#76]
Random dump, to sort out further:

- https://www.w3.org/Submission/SWRL/
- http://wiki.ruleml.org/index.php/RuleML_Home
- http://techinvestlab.ru/dot15926Editor
- https://en.wikipedia.org/wiki/Semantic_reasoner
- https://www.sciencedirect.com/science/article/pii/S1877050916325182

**Comment by maximveksler** [comment]
- Possibly under a "previous work" or "history" section with things like https://en.wikipedia.org/wiki/F-logic

**Comment by zacharywhitley** [comment]
Moving all the links listed over to [awesomelets](https://github.com/semantalytics/awesome-semantic-web/issues/81) issue. Improve rules is aspirational and there is no clear criteria for closing this issue. Perhaps these things should be captured in a wiki page under "focus areas" or something like that.
