### ISSUE TITLE
Remove jobs section

### ISSUE THREAD

**Issue by zacharywhitley** [semantalytics/awesome-semantic-web#78]
While I understand the desire to add a jobs section it's far too dynamic to keep up to date. Job postings are a great way to get some information on what companies are looking to work with semantic web technologies. The best I would be able to offer here would be  a link to http://indeed.com with some suggested keywords rdf/owl/ontolgy/semantic web/sparql etc

**Comment by maximveksler** [comment]
Yes, hopefully the volume will grow enough to justify a dedicated community resource in the likes of https://remoteok.io or a sub forum on graph.vodka.
