### ISSUE TITLE
Add Activity Streams

### ISSUE THREAD

**Issue by zacharywhitley** [semantalytics/awesome-semantic-web#80]
https://www.w3.org/TR/activitystreams-core/

**Comment by maximveksler** [comment]
Might not be related to RDF ?

**Comment by zacharywhitley** [comment]
https://www.w3.org/TR/activitystreams-core/

> This specification describes a JSON-based [RFC7159] serialization syntax for the Activity Vocabulary that conforms to a subset of [JSON-LD] syntax constraints but does not require JSON-LD processing. While other serialization forms are possible, such alternatives are not discussed by this document.

I'm guessing that they specified a subset of JSON-LD so that it wouldn't require RDF tooling to process but I think you could if you wanted. It's interesting that they seem to minimize the connection to RDF the same way that JSON-LD tried it.

**Comment by zacharywhitley** [comment]
Moved to #81
